spring.application.name=${APP_HOGWARTS:hogwarts}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/Hogwarts}
spring.datasource.username=${DATABASE_USERNAME:student}
spring.datasource.password=${DATABASE_PASSWORD:chocolatefrog}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL:update}
students.avatar.dir.path=${AVATAR_DIR_PATH:avatars}